# Generated by Django 4.2.9 on 2024-03-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOptionValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('defaultoption', models.BooleanField(default=False)),
                ('pricechange', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.option')),
                ('optionvalue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.optionvalue')),
            ],
            options={
                'unique_together': {('item', 'option', 'optionvalue')},
            },
        ),
    ]
